import React, { useState } from 'react';
import { 
  ArrowLeft, BarChart2, Calendar, RefreshCw, Download, Printer, 
  TrendingUp, TrendingDown, Wallet, ShoppingBag, ShieldCheck, Lock, X 
} from 'lucide-react';

export default function RevenueReportDetails({ onBack }) {
  const [isDrawerOpen, setIsDrawerOpen] = useState(false);

  const toggleDrawer = () => {
    setIsDrawerOpen(!isDrawerOpen);
  };

  return (
    <div className="bg-zinc-50 dark:bg-zinc-950 min-h-screen animate-fade-in pb-24">
      {/* Top Navigation Anchor */}
      <header className="w-full top-0 sticky z-40 bg-white dark:bg-zinc-950 border-b border-zinc-200 dark:border-zinc-800 shadow-sm">
        <div className="flex justify-between items-center px-6 py-4 w-full max-w-[1440px] mx-auto">
          <div className="flex items-center gap-4">
            <button 
              onClick={onBack}
              className="p-2 rounded-full hover:bg-zinc-100 dark:hover:bg-zinc-800 transition-colors cursor-pointer active:scale-90"
            >
              <ArrowLeft className="text-[var(--primary)]" size={24} />
            </button>
            <div className="flex items-center gap-2">
              <BarChart2 className="text-[var(--primary)]" size={32} />
              <h1 className="text-2xl font-black text-[var(--primary)] hidden sm:block">Franchise Analytics</h1>
              <h1 className="text-xl font-black text-[var(--primary)] sm:hidden">Analytics</h1>
            </div>
          </div>
          <div className="flex items-center gap-4">
            <div className="text-right hidden md:block">
              <p className="text-[10px] font-bold text-zinc-500 dark:text-zinc-400 uppercase tracking-wider mb-0.5">Report Generated By</p>
              <p className="text-sm font-bold text-zinc-900 dark:text-zinc-100">Super Admin</p>
            </div>
            <div className="w-10 h-10 rounded-full bg-[var(--primary)]/10 dark:bg-[var(--primary)]/20 flex items-center justify-center text-[var(--primary)] font-bold border border-[var(--primary)]/20 shadow-sm shrink-0">
              SA
            </div>
          </div>
        </div>
      </header>

      <main className="max-w-[1440px] mx-auto p-4 md:p-8 space-y-8">
        
        {/* Header Info & Controls */}
        <div className="flex flex-col lg:flex-row justify-between items-start lg:items-end gap-6">
          <div>
            <p className="text-xs font-bold text-[var(--primary)] uppercase tracking-widest mb-2">Detailed Analysis</p>
            <h2 className="text-3xl font-black text-zinc-900 dark:text-zinc-100">Revenue Breakdown Report</h2>
            <div className="flex flex-wrap items-center gap-3 mt-3">
              <span className="flex items-center gap-2 bg-white dark:bg-zinc-900 border border-zinc-200 dark:border-zinc-800 shadow-sm px-3 py-1.5 rounded-lg text-zinc-600 dark:text-zinc-300 text-xs font-medium">
                <Calendar size={14} className="text-[var(--primary)]" />
                Oct 01 - Oct 31, 2023
              </span>
              <span className="flex items-center gap-2 bg-white dark:bg-zinc-900 border border-zinc-200 dark:border-zinc-800 shadow-sm px-3 py-1.5 rounded-lg text-zinc-600 dark:text-zinc-300 text-xs font-medium">
                <RefreshCw size={14} className="text-[var(--primary)]" />
                Last Sync: 5 mins ago
              </span>
            </div>
          </div>
          <div className="flex gap-3 w-full lg:w-auto">
            <button className="flex-1 lg:flex-none flex items-center justify-center gap-2 px-4 py-2.5 rounded-xl border border-zinc-200 dark:border-zinc-700 bg-white dark:bg-zinc-900 text-zinc-700 dark:text-zinc-300 hover:bg-zinc-50 dark:hover:bg-zinc-800 transition-colors font-bold text-sm shadow-sm">
              <Download size={18} />
              <span>Export PDF</span>
            </button>
            <button className="flex-1 lg:flex-none flex items-center justify-center gap-2 px-4 py-2.5 rounded-xl bg-[var(--primary)] text-white hover:brightness-110 active:scale-95 transition-all font-bold text-sm shadow-md shadow-[var(--primary)]/20">
              <Printer size={18} />
              <span>Print Report</span>
            </button>
          </div>
        </div>

        {/* Bento Grid Layout */}
        <div className="grid grid-cols-12 gap-6">
          
          {/* 1. Revenue Overview */}
          <div className="col-span-12 xl:col-span-8 bg-white dark:bg-zinc-900 border border-zinc-200 dark:border-zinc-800 rounded-2xl p-6 shadow-sm hover:shadow-md transition-shadow relative overflow-hidden group">
            <div className="flex justify-between items-start mb-8">
              <div>
                <h3 className="text-xl font-bold text-zinc-900 dark:text-zinc-100 mb-1">Revenue Overview</h3>
                <p className="text-sm font-medium text-zinc-500 dark:text-zinc-400">Gross Achievement vs Target</p>
              </div>
              <div className="text-right">
                <span className="text-4xl font-black text-[var(--primary)]">92%</span>
                <p className="text-xs font-bold text-zinc-500 dark:text-zinc-400 uppercase mt-1 tracking-wider">Of Monthly Target</p>
              </div>
            </div>
            
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 mt-4">
              <div className="p-5 rounded-xl bg-zinc-50 dark:bg-zinc-950/50 border border-zinc-100 dark:border-zinc-800/50">
                <p className="text-xs font-bold text-zinc-500 dark:text-zinc-400 mb-2 uppercase tracking-wider">Gross Revenue</p>
                <p className="text-3xl font-black text-zinc-900 dark:text-zinc-100">$482,900.00</p>
                <div className="flex items-center gap-1.5 text-emerald-600 dark:text-emerald-500 mt-3 font-bold text-sm">
                  <TrendingUp size={16} />
                  <span>+12.4% vs Prev Month</span>
                </div>
              </div>
              <div className="p-5 rounded-xl bg-zinc-50 dark:bg-zinc-950/50 border border-zinc-100 dark:border-zinc-800/50">
                <p className="text-xs font-bold text-zinc-500 dark:text-zinc-400 mb-2 uppercase tracking-wider">Net Revenue</p>
                <p className="text-3xl font-black text-zinc-900 dark:text-zinc-100">$444,268.00</p>
                <div className="flex items-center gap-1.5 text-rose-600 dark:text-rose-500 mt-3 font-bold text-sm">
                  <TrendingDown size={16} />
                  <span>-2.1% from Gross Gap</span>
                </div>
              </div>
            </div>
            
            <div className="mt-8">
              <div className="w-full h-3 bg-zinc-100 dark:bg-zinc-800 rounded-full overflow-hidden relative">
                <div className="absolute top-0 left-0 h-full bg-[var(--primary)] rounded-full transition-all duration-1000" style={{ width: '92%' }}></div>
              </div>
              <div className="flex justify-between mt-3">
                <span className="text-xs font-bold text-zinc-500 dark:text-zinc-400">$0</span>
                <span className="text-xs font-bold text-zinc-500 dark:text-zinc-400">Target: $525,000</span>
              </div>
            </div>
          </div>

          {/* 2. Profitability Analysis */}
          <div className="col-span-12 md:col-span-6 xl:col-span-4 bg-[var(--primary)] text-white rounded-2xl p-6 shadow-md shadow-[var(--primary)]/20 flex flex-col justify-between relative overflow-hidden">
            <div className="absolute -right-6 -top-6 opacity-10 pointer-events-none">
              <Wallet size={180} />
            </div>
            <div className="relative z-10">
              <h3 className="text-xl font-bold mb-1">Profitability Analysis</h3>
              <p className="text-sm font-medium text-white/80">Final margin after all deductions</p>
            </div>
            
            <div className="my-8 relative z-10">
              <div className="flex items-end gap-3">
                <span className="text-5xl font-black leading-none">18.5%</span>
                <span className="text-lg font-bold mb-1 opacity-90">Margin</span>
              </div>
              <p className="text-sm font-medium mt-3 text-white/90">Net profit of $82,190.00 this month</p>
            </div>
            
            <div className="space-y-3 relative z-10">
              <div className="flex justify-between items-center py-2 border-b border-white/20">
                <span className="text-sm font-bold text-white/90">Operating Costs</span>
                <span className="font-mono text-sm font-bold">$242,000.00</span>
              </div>
              <div className="flex justify-between items-center py-2 border-b border-white/20">
                <span className="text-sm font-bold text-white/90">Commissions</span>
                <span className="font-mono text-sm font-bold">$120,078.00</span>
              </div>
              <div className="flex justify-between items-center py-2">
                <span className="text-sm font-bold text-white/90">Net Profit</span>
                <span className="font-mono text-lg font-black">$82,190.00</span>
              </div>
            </div>
          </div>

          {/* 3. Sales Breakdown */}
          <div className="col-span-12 md:col-span-6 xl:col-span-4 bg-white dark:bg-zinc-900 border border-zinc-200 dark:border-zinc-800 rounded-2xl p-6 shadow-sm flex flex-col">
            <h3 className="text-xl font-bold text-zinc-900 dark:text-zinc-100 mb-6">Sales Breakdown</h3>
            <div className="space-y-6 flex-1">
              <div className="space-y-2">
                <div className="flex justify-between text-sm font-bold">
                  <span className="text-zinc-600 dark:text-zinc-400">Online Store</span>
                  <span className="text-zinc-900 dark:text-zinc-100">52%</span>
                </div>
                <div className="w-full h-2.5 bg-zinc-100 dark:bg-zinc-800 rounded-full overflow-hidden">
                  <div className="h-full bg-[var(--primary)] rounded-full" style={{ width: '52%' }}></div>
                </div>
              </div>
              <div className="space-y-2">
                <div className="flex justify-between text-sm font-bold">
                  <span className="text-zinc-600 dark:text-zinc-400">In-Store Purchase</span>
                  <span className="text-zinc-900 dark:text-zinc-100">34%</span>
                </div>
                <div className="w-full h-2.5 bg-zinc-100 dark:bg-zinc-800 rounded-full overflow-hidden">
                  <div className="h-full bg-zinc-500 dark:bg-zinc-400 rounded-full" style={{ width: '34%' }}></div>
                </div>
              </div>
              <div className="space-y-2">
                <div className="flex justify-between text-sm font-bold">
                  <span className="text-zinc-600 dark:text-zinc-400">Third-Party Delivery</span>
                  <span className="text-zinc-900 dark:text-zinc-100">14%</span>
                </div>
                <div className="w-full h-2.5 bg-zinc-100 dark:bg-zinc-800 rounded-full overflow-hidden">
                  <div className="h-full bg-orange-500 rounded-full" style={{ width: '14%' }}></div>
                </div>
              </div>
            </div>
            
            <div className="mt-8 pt-6 border-t border-zinc-200 dark:border-zinc-800">
              <div className="flex items-center gap-4">
                <div className="p-3 bg-zinc-50 dark:bg-zinc-950/50 rounded-xl border border-zinc-100 dark:border-zinc-800/50">
                  <ShoppingBag className="text-[var(--primary)]" size={24} />
                </div>
                <div>
                  <p className="font-mono text-lg font-bold text-zinc-900 dark:text-zinc-100">4,821 Orders</p>
                  <p className="text-xs font-medium text-zinc-500 dark:text-zinc-400 mt-1">Avg. Order Value: $100.16</p>
                </div>
              </div>
            </div>
          </div>

          {/* 4. Tax & Fees Details */}
          <div className="col-span-12 md:col-span-6 xl:col-span-4 bg-white dark:bg-zinc-900 border border-zinc-200 dark:border-zinc-800 rounded-2xl p-6 shadow-sm overflow-hidden flex flex-col">
            <h3 className="text-xl font-bold text-zinc-900 dark:text-zinc-100 mb-6">Tax & Fees</h3>
            <div className="overflow-x-auto flex-1">
              <table className="w-full">
                <thead className="border-b border-zinc-200 dark:border-zinc-800">
                  <tr>
                    <th className="text-left text-xs font-bold text-zinc-500 dark:text-zinc-400 uppercase tracking-wider pb-3">Type</th>
                    <th className="text-right text-xs font-bold text-zinc-500 dark:text-zinc-400 uppercase tracking-wider pb-3">Amount</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-zinc-100 dark:divide-zinc-800/50">
                  <tr>
                    <td className="py-4 text-sm font-bold text-zinc-900 dark:text-zinc-100">GST (Total)</td>
                    <td className="py-4 font-mono text-sm font-bold text-right text-zinc-900 dark:text-zinc-100">$43,461.00</td>
                  </tr>
                  <tr>
                    <td className="py-3 text-sm font-medium text-zinc-600 dark:text-zinc-400 pl-4">CGST (9%)</td>
                    <td className="py-3 font-mono text-sm font-medium text-right text-zinc-600 dark:text-zinc-400">$21,730.50</td>
                  </tr>
                  <tr>
                    <td className="py-3 text-sm font-medium text-zinc-600 dark:text-zinc-400 pl-4">SGST (9%)</td>
                    <td className="py-3 font-mono text-sm font-medium text-right text-zinc-600 dark:text-zinc-400">$21,730.50</td>
                  </tr>
                  <tr>
                    <td className="py-4 text-sm font-bold text-zinc-900 dark:text-zinc-100">Service Charge</td>
                    <td className="py-4 font-mono text-sm font-bold text-right text-zinc-900 dark:text-zinc-100">$12,072.00</td>
                  </tr>
                </tbody>
                <tfoot className="border-t-2 border-zinc-200 dark:border-zinc-800">
                  <tr>
                    <td className="py-4 text-sm font-black text-zinc-900 dark:text-zinc-100">Total Deductions</td>
                    <td className="py-4 font-mono text-lg font-black text-right text-zinc-900 dark:text-zinc-100">$55,533.00</td>
                  </tr>
                </tfoot>
              </table>
            </div>
          </div>

          {/* 5. Refund Analysis */}
          <div className="col-span-12 md:col-span-6 xl:col-span-4 bg-white dark:bg-zinc-900 border border-zinc-200 dark:border-zinc-800 rounded-2xl p-6 shadow-sm flex flex-col">
            <div className="flex justify-between items-center mb-6">
              <h3 className="text-xl font-bold text-zinc-900 dark:text-zinc-100">Refund Analysis</h3>
              <span className="bg-rose-50 dark:bg-rose-900/20 text-rose-600 dark:text-rose-400 px-2.5 py-1 rounded-md text-xs font-bold border border-rose-200 dark:border-rose-800/30 shadow-sm">
                High Impact
              </span>
            </div>
            
            <div className="mb-6 p-5 bg-rose-50 dark:bg-rose-950/30 rounded-xl border border-rose-100 dark:border-rose-900/30">
              <p className="text-xs font-black text-rose-600 dark:text-rose-500 uppercase tracking-widest mb-1">Net Impact</p>
              <p className="text-3xl font-black text-rose-700 dark:text-rose-400">-$18,240.00</p>
              <p className="text-sm font-medium text-rose-600 dark:text-rose-500 opacity-80 mt-2">Total of 214 refund events</p>
            </div>
            
            <div className="space-y-4 flex-1">
              <p className="text-xs font-bold text-zinc-500 dark:text-zinc-400 uppercase tracking-wider">Top Refund Reasons</p>
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-3">
                  <div className="w-2.5 h-2.5 rounded-full bg-rose-500"></div>
                  <span className="text-sm font-bold text-zinc-700 dark:text-zinc-300">Order Cancellation</span>
                </div>
                <span className="font-mono text-sm font-bold text-zinc-900 dark:text-zinc-100">48%</span>
              </div>
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-3">
                  <div className="w-2.5 h-2.5 rounded-full bg-orange-500"></div>
                  <span className="text-sm font-bold text-zinc-700 dark:text-zinc-300">Damaged Goods</span>
                </div>
                <span className="font-mono text-sm font-bold text-zinc-900 dark:text-zinc-100">32%</span>
              </div>
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-3">
                  <div className="w-2.5 h-2.5 rounded-full bg-amber-500"></div>
                  <span className="text-sm font-bold text-zinc-700 dark:text-zinc-300">Incorrect Item</span>
                </div>
                <span className="font-mono text-sm font-bold text-zinc-900 dark:text-zinc-100">20%</span>
              </div>
            </div>
            
            <button 
              onClick={toggleDrawer}
              className="w-full mt-8 py-3 rounded-xl border-2 border-zinc-200 dark:border-zinc-700 text-zinc-700 dark:text-zinc-300 font-bold text-sm hover:bg-zinc-50 dark:hover:bg-zinc-800 transition-colors active:scale-[0.98]"
            >
              View Full Refund Audit
            </button>
          </div>

        </div>

        {/* Audit Trail Footer */}
        <footer className="mt-8 pt-8 border-t border-zinc-200 dark:border-zinc-800 flex flex-col md:flex-row justify-between items-center gap-6">
          <div className="flex flex-wrap justify-center md:justify-start items-center gap-6">
            <div className="flex items-center gap-2 text-zinc-500 dark:text-zinc-400">
              <ShieldCheck size={18} />
              <p className="text-sm font-medium">Authenticated Report</p>
            </div>
            <div className="flex items-center gap-2 text-zinc-500 dark:text-zinc-400">
              <Lock size={18} />
              <p className="text-sm font-medium">SHA-256 Encrypted</p>
            </div>
          </div>
          <div className="flex items-center gap-4 text-center md:text-right">
            <p className="text-sm font-medium text-zinc-500 dark:text-zinc-400">System Version: <span className="font-bold text-zinc-900 dark:text-zinc-100">v2.4.1</span></p>
            <div className="h-4 w-px bg-zinc-300 dark:bg-zinc-700"></div>
            <p className="text-sm font-medium text-zinc-500 dark:text-zinc-400">Instance: <span className="font-bold text-zinc-900 dark:text-zinc-100">Node-04_Production</span></p>
          </div>
        </footer>
      </main>

      {/* Detailed Insights Floating Drawer (Audit Logs) */}
      <div 
        className={`fixed right-0 top-0 h-full w-full sm:w-[450px] bg-white dark:bg-zinc-950 border-l border-zinc-200 dark:border-zinc-800 shadow-2xl z-[100] transform transition-transform duration-300 flex flex-col ${isDrawerOpen ? 'translate-x-0' : 'translate-x-full'}`}
      >
        <div className="p-6 md:p-8 flex flex-col h-full">
          <div className="flex justify-between items-center mb-8">
            <h4 className="text-2xl font-bold text-zinc-900 dark:text-zinc-100">Audit Log Details</h4>
            <button 
              className="p-2 rounded-full hover:bg-zinc-100 dark:hover:bg-zinc-800 text-zinc-500 dark:text-zinc-400 transition-colors"
              onClick={toggleDrawer}
            >
              <X size={24} />
            </button>
          </div>
          
          <div className="space-y-4 overflow-y-auto custom-scrollbar flex-1 pr-2">
            
            <div className="p-5 rounded-xl bg-zinc-50 dark:bg-zinc-900 border border-zinc-200 dark:border-zinc-800">
              <div className="flex justify-between mb-3">
                <span className="text-[10px] font-black text-[var(--primary)] uppercase tracking-wider bg-[var(--primary)]/10 px-2 py-0.5 rounded">Action</span>
                <span className="text-xs font-bold text-zinc-500 dark:text-zinc-400">10:45 AM</span>
              </div>
              <p className="text-sm font-bold text-zinc-900 dark:text-zinc-100">Manual Adjustment Approved</p>
              <p className="text-sm font-medium text-zinc-600 dark:text-zinc-400 mt-2">Super Admin adjusted Refund #4021 from 'Pending' to 'Settled'.</p>
            </div>
            
            <div className="p-5 rounded-xl bg-zinc-50 dark:bg-zinc-900 border border-zinc-200 dark:border-zinc-800 opacity-70 hover:opacity-100 transition-opacity">
              <div className="flex justify-between mb-3">
                <span className="text-[10px] font-black text-amber-600 uppercase tracking-wider bg-amber-500/10 px-2 py-0.5 rounded">Sync</span>
                <span className="text-xs font-bold text-zinc-500 dark:text-zinc-400">10:40 AM</span>
              </div>
              <p className="text-sm font-bold text-zinc-900 dark:text-zinc-100">POS Data Ingested</p>
              <p className="text-sm font-medium text-zinc-600 dark:text-zinc-400 mt-2">Data from 42 outlets successfully synced with central repository.</p>
            </div>

            <div className="p-5 rounded-xl bg-zinc-50 dark:bg-zinc-900 border border-zinc-200 dark:border-zinc-800 opacity-70 hover:opacity-100 transition-opacity">
              <div className="flex justify-between mb-3">
                <span className="text-[10px] font-black text-rose-600 uppercase tracking-wider bg-rose-500/10 px-2 py-0.5 rounded">Alert</span>
                <span className="text-xs font-bold text-zinc-500 dark:text-zinc-400">09:15 AM</span>
              </div>
              <p className="text-sm font-bold text-zinc-900 dark:text-zinc-100">Refund Spike Detected</p>
              <p className="text-sm font-medium text-zinc-600 dark:text-zinc-400 mt-2">Unusual volume of order cancellations detected in North Region.</p>
            </div>

          </div>
          
          <div className="pt-6 mt-4 border-t border-zinc-200 dark:border-zinc-800">
            <button className="w-full py-4 bg-[var(--primary)] text-white rounded-xl font-bold shadow-md hover:brightness-110 active:scale-[0.98] transition-all">
              Verify Chain of Custody
            </button>
          </div>
        </div>
      </div>
      
      {/* Drawer Overlay */}
      {isDrawerOpen && (
        <div 
          className="fixed inset-0 bg-black/40 backdrop-blur-sm z-[90] transition-opacity"
          onClick={toggleDrawer}
        ></div>
      )}

    </div>
  );
}
